/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbdad5",
        "surface-container": "#efeee9",
        "on-surface": "#1b1c19",
        "tertiary-fixed": "#e4e2e1",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b9ccb0",
        "on-tertiary-fixed-variant": "#474747",
        "on-surface-variant": "#444841",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c8c6c6",
        "inverse-surface": "#30312e",
        "secondary-fixed": "#ffdf9f",
        "outline": "#747870",
        "surface-container-low": "#f5f4ef",
        "primary-fixed": "#d5e8cb",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#3b4b36",
        "surface-tint": "#52634c",
        "primary-fixed-dim": "#b9ccb0",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#e7c274",
        "secondary-container": "#ffd888",
        "tertiary-container": "#1b1c1c",
        "surface-variant": "#e3e3de",
        "surface-container-high": "#e9e8e3",
        "background": "#faf9f4",
        "secondary": "#765a17",
        "primary": "#000000",
        "on-primary-fixed": "#101f0d",
        "surface-container-highest": "#e3e3de",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-background": "#1b1c19",
        "on-secondary-container": "#795d19",
        "on-primary-container": "#778970",
        "on-secondary-fixed-variant": "#5b4300",
        "surface": "#faf9f4",
        "on-tertiary-container": "#848383",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#261a00",
        "on-primary": "#ffffff",
        "surface-bright": "#faf9f4",
        "outline-variant": "#c4c8be",
        "on-tertiary": "#ffffff",
        "primary-container": "#101f0d",
        "inverse-on-surface": "#f2f1ec"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
};

export default config;
